from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(828, 506)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame_superior = QFrame(self.centralwidget)
        self.frame_superior.setObjectName(u"frame_superior")
        self.frame_superior.setStyleSheet(u"background-color: rgb(170, 170, 255);")
        self.frame_superior.setFrameShape(QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame_superior)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.BOTON_LOGO = QPushButton(self.frame_superior)
        self.BOTON_LOGO.setObjectName(u"BOTON_LOGO")
        self.BOTON_LOGO.setMaximumSize(QSize(180, 30))
        self.BOTON_LOGO.setStyleSheet(u"background-color: rgba(255, 0,0, 2);")
        icon = QIcon()
        icon.addFile(u"Fotos\principal/logo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.BOTON_LOGO.setIcon(icon)
        self.BOTON_LOGO.setIconSize(QSize(100, 30))

        self.horizontalLayout_2.addWidget(self.BOTON_LOGO)

        self.horizontalSpacer = QSpacerItem(338, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer)

        self.boton_minimizar = QPushButton(self.frame_superior)
        self.boton_minimizar.setObjectName(u"boton_minimizar")
        self.boton_minimizar.setStyleSheet(u"background-color: rgb(240, 209, 234);")
        icon1 = QIcon()
        icon1.addFile(u"Fotos\principal/ximi (16).png", QSize(), QIcon.Normal, QIcon.Off)
        self.boton_minimizar.setIcon(icon1)
        self.boton_minimizar.setIconSize(QSize(30, 30))

        self.horizontalLayout_2.addWidget(self.boton_minimizar)

        self.boton_eliminar = QPushButton(self.frame_superior)
        self.boton_eliminar.setObjectName(u"boton_eliminar")
        self.boton_eliminar.setStyleSheet(u"background-color: rgb(240, 209, 234);")
        icon3 = QIcon()
        icon3.addFile(u"Fotos\principal/ximi (14).png", QSize(), QIcon.Normal, QIcon.Off)
        self.boton_eliminar.setIcon(icon3)
        self.boton_eliminar.setIconSize(QSize(32, 32))

        self.horizontalLayout_2.addWidget(self.boton_eliminar)


        self.verticalLayout.addWidget(self.frame_superior)

        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame_2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.frame_2)
        self.frame.setObjectName(u"frame")
        self.frame.setMinimumSize(QSize(150, 0))
        self.frame.setMaximumSize(QSize(100, 16777215))
        self.frame.setStyleSheet(u"\n"
"background-color: rgb(170, 170, 255);")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.BOTON_TABLA = QPushButton(self.frame)
        self.BOTON_TABLA.setObjectName(u"BOTON_TABLA")
        self.BOTON_TABLA.setStyleSheet(u"border-radius: 10px; background: rgb(240, 209, 234)")
        icon4 = QIcon()
        icon4.addFile(u"Fotos\principal/ximi (6).png", QSize(), QIcon.Normal, QIcon.Off)
        self.BOTON_TABLA.setIcon(icon4)
        self.BOTON_TABLA.setIconSize(QSize(32, 32))

        self.verticalLayout_3.addWidget(self.BOTON_TABLA)

        self.BOTON_rEGISTRAR = QPushButton(self.frame)
        self.BOTON_rEGISTRAR.setObjectName(u"BOTON_rEGISTRAR")
        self.BOTON_rEGISTRAR.setStyleSheet(u"border-radius: 10px; background: rgb(240, 209, 234)")
        icon5 = QIcon()
        icon5.addFile(u"Fotos\principal/Registro.png", QSize(), QIcon.Normal, QIcon.Off)
        self.BOTON_rEGISTRAR.setIcon(icon5)
        self.BOTON_rEGISTRAR.setIconSize(QSize(32, 32))

        self.verticalLayout_3.addWidget(self.BOTON_rEGISTRAR)

        self.BOTON_ACTUALIZAR = QPushButton(self.frame)
        self.BOTON_ACTUALIZAR.setObjectName(u"BOTON_ACTUALIZAR")
        self.BOTON_ACTUALIZAR.setStyleSheet(u"border-radius: 10px; background: rgb(240, 209, 234)")
        icon6 = QIcon()
        icon6.addFile(u"Fotos\principal/ximi (13).png", QSize(), QIcon.Normal, QIcon.Off)
        self.BOTON_ACTUALIZAR.setIcon(icon6)
        self.BOTON_ACTUALIZAR.setIconSize(QSize(32, 32))

        self.verticalLayout_3.addWidget(self.BOTON_ACTUALIZAR)

        self.BOTON_eLIMINAR = QPushButton(self.frame)
        self.BOTON_eLIMINAR.setObjectName(u"BOTON_eLIMINAR")
        self.BOTON_eLIMINAR.setStyleSheet(u"border-radius: 10px; background: rgb(240, 209, 234)")
        icon7 = QIcon()
        icon7.addFile(u"Fotos\principal/ximi (12).png", QSize(), QIcon.Normal, QIcon.Off)
        self.BOTON_eLIMINAR.setIcon(icon7)
        self.BOTON_eLIMINAR.setIconSize(QSize(32, 32))

        self.verticalLayout_3.addWidget(self.BOTON_eLIMINAR)


        self.horizontalLayout.addWidget(self.frame)

        self.frame_3 = QFrame(self.frame_2)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.stackedWidget = QStackedWidget(self.frame_3)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setStyleSheet(u"background-color: rgb(255, 255, 0);\n"
"background-color: rgb(170, 170, 255);")
        self.pagina1 = QWidget()
        self.pagina1.setObjectName(u"pagina1")
        self.verticalLayout_4 = QVBoxLayout(self.pagina1)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")





        self.pagina1 = QWidget()
        self.pagina1.setObjectName(u"pagina1")
        self.verticalLayout_4 = QVBoxLayout(self.pagina1)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.frame_4 = QFrame(self.pagina1)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.Btn_Siguiente = QPushButton(self.frame_4)
        self.Btn_Siguiente.setObjectName(u"Btn_Siguiente")
        self.Btn_Siguiente.setGeometry(QRect(474, 370, 121, 23))
        font = QFont()
        font.setFamily(u"Fixedsys")
        self.Btn_Siguiente.setFont(font)
        self.Btn_6 = QRadioButton(self.frame_4)
        self.Btn_6.setObjectName(u"Btn_6")
        self.Btn_6.setGeometry(QRect(570, 110, 51, 51))
        icon8 = QIcon()
        icon8.addFile(u"Fotos/istockphoto-1352019756-612x612.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.Btn_6.setIcon(icon8)
        self.Btn_6.setIconSize(QSize(32, 48))
        self.Btn_9 = QRadioButton(self.frame_4)
        self.Btn_9.setObjectName(u"Btn_9")
        self.Btn_9.setGeometry(QRect(570, 160, 51, 51))
        icon9 = QIcon()
        icon9.addFile(u"Fotos/96048633-dibujo-de-botellas-de-jab\u00f3n-l\u00edquido-dispensador-de-jab\u00f3n.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.Btn_9.setIcon(icon9)
        self.Btn_9.setIconSize(QSize(32, 48))
        self.tableWidget = QTableWidget(self.frame_4)
        if (self.tableWidget.columnCount() < 5):
            self.tableWidget.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(0, 60, 421, 331))
        self.tableWidget.setMinimumSize(QSize(421, 0))
        self.tableWidget.setStyleSheet(u"")
        self.tableWidget.setWordWrap(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget.horizontalHeader().setProperty("showSortIndicator", False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(10)
        self.spinBox = QSpinBox(self.frame_4)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(520, 260, 71, 22))
        self.Btn_1 = QRadioButton(self.frame_4)
        self.Btn_1.setObjectName(u"Btn_1")
        self.Btn_1.setGeometry(QRect(430, 60, 51, 51))
        icon10 = QIcon()
        icon10.addFile(u"Fotos/medicine-dropper-bottle-free-vector.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.Btn_1.setIcon(icon10)
        self.Btn_1.setIconSize(QSize(32, 48))
        self.label_13 = QLabel(self.frame_4)
        self.label_13.setObjectName(u"label_13")
        
        self.label_13.setGeometry(QRect(170, 0, 271, 51))
        font1 = QFont()
        font1.setFamily(u"Segoe UI Black")
        font1.setPointSize(26)
        font1.setBold(True)
        font1.setWeight(75)
        self.label_13.setFont(font1)
        self.label_13.setStyleSheet(u"color: rgb(0, 170, 127);")
        self.Btn_7 = QRadioButton(self.frame_4)
        self.Btn_7.setObjectName(u"Btn_7")
        self.Btn_7.setGeometry(QRect(430, 160, 51, 51))
        icon11 = QIcon()
        icon11.addFile(u"Fotos/gratis-png-frasco-gotero-mapa-material-acuario.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Btn_7.setIcon(icon11)
        self.Btn_7.setIconSize(QSize(48, 48))
        self.Btn_7.setAutoRepeatDelay(100)
        self.Btn_12 = QRadioButton(self.frame_4)
        self.Btn_12.setObjectName(u"Btn_12")
        self.Btn_12.setGeometry(QRect(570, 210, 61, 51))
        self.Btn_12.setIcon(icon10)
        self.Btn_12.setIconSize(QSize(32, 48))
        self.Btn_8 = QRadioButton(self.frame_4)
        self.Btn_8.setObjectName(u"Btn_8")
        self.Btn_8.setGeometry(QRect(500, 160, 51, 51))
        icon12 = QIcon()
        icon12.addFile(u"Fotos/gettyimages-1303772648-612x612.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.Btn_8.setIcon(icon12)
        self.Btn_8.setIconSize(QSize(32, 48))
        self.Btn_4 = QRadioButton(self.frame_4)
        self.Btn_4.setObjectName(u"Btn_4")
        self.Btn_4.setGeometry(QRect(430, 110, 51, 51))
        icon13 = QIcon()
        icon13.addFile(u"Fotos/mascarilla-negra-pilaten.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.Btn_4.setIcon(icon13)
        self.Btn_4.setIconSize(QSize(48, 38))
        self.Btn_10 = QRadioButton(self.frame_4)
        self.Btn_10.setObjectName(u"Btn_10")
        self.Btn_10.setGeometry(QRect(430, 210, 51, 51))
        icon14 = QIcon()
        icon14.addFile(u"Fotos/3228f4903d1701037fa30c2ead90cd95.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Btn_10.setIcon(icon14)
        self.Btn_10.setIconSize(QSize(32, 48))
        self.Btn_5 = QRadioButton(self.frame_4)
        self.Btn_5.setObjectName(u"Btn_5")
        self.Btn_5.setGeometry(QRect(500, 110, 51, 51))
        icon15 = QIcon()
        icon15.addFile(u"Fotos/istockphoto-1404980792-612x612.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.Btn_5.setIcon(icon15)
        self.Btn_5.setIconSize(QSize(48, 48))
        self.Btn_Eliminar = QPushButton(self.frame_4)
        self.Btn_Eliminar.setObjectName(u"Btn_Eliminar")
        self.Btn_Eliminar.setGeometry(QRect(430, 330, 211, 31))
        font2 = QFont()
        font2.setFamily(u"Fixedsys")
        font2.setPointSize(11)
        font2.setBold(True)
        font2.setWeight(75)
        self.Btn_Eliminar.setFont(font2)
        self.label = QLabel(self.frame_4)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(430, 260, 91, 21))
        font3 = QFont()
        font3.setPointSize(14)
        self.label.setFont(font3)
        self.push = QPushButton(self.frame_4)
        self.push.setObjectName(u"push")
        self.push.setGeometry(QRect(430, 290, 211, 31))
        self.push.setFont(font2)
        self.Btn_3 = QRadioButton(self.frame_4)
        self.Btn_3.setObjectName(u"Btn_3")
        self.Btn_3.setGeometry(QRect(570, 60, 51, 51))
        icon16 = QIcon()
        icon16.addFile(u"Fotos/pngtree-perfume-vector-illustration-in-hand-drawn-style-png-image_2897181.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Btn_3.setIcon(icon16)
        self.Btn_3.setIconSize(QSize(48, 48))
        self.Btn_11 = QRadioButton(self.frame_4)
        self.Btn_11.setObjectName(u"Btn_11")
        self.Btn_11.setGeometry(QRect(500, 210, 51, 51))
        self.Btn_11.setIcon(icon10)
        self.Btn_11.setIconSize(QSize(32, 48))
        self.Btn_2 = QRadioButton(self.frame_4)
        self.Btn_2.setObjectName(u"Btn_2")
        self.Btn_2.setGeometry(QRect(500, 60, 51, 51))
        icon17 = QIcon()
        icon17.addFile(u"Fotos/suero-de-vitamina-c-esencia-hidratante-acido-de-la-fruta-para-la-cara-producto-natural-para-el-cuidado-de-la-piel-rutina-de-la-manana-producto-organico-dibujado-a-mano-vector-2h0x4ed.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.Btn_2.setIcon(icon17)
        self.Btn_2.setIconSize(QSize(48, 48))

        self.verticalLayout_4.addWidget(self.frame_4)

        self.stackedWidget.addWidget(self.pagina1)


        self.pagina_RE = QFrame(self.centralwidget)
        self.pagina_RE.setObjectName(u"pagina_RE")
        self.pagina_RE.setFrameShape(QFrame.StyledPanel)
        self.pagina_RE.setFrameShadow(QFrame.Raised)
        self.tabla_inventario = QTableWidget(self.pagina_RE)
        if (self.tabla_inventario.columnCount() < 5):
            self.tabla_inventario.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.tabla_inventario.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tabla_inventario.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tabla_inventario.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tabla_inventario.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tabla_inventario.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.tabla_inventario.setObjectName(u"tabla_inventario")
        self.tabla_inventario.setGeometry(QRect(20, 60, 561, 310))
        self.tabla_inventario.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label = QLabel(self.pagina_RE)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(180, 10, 221, 41))
        self.label.setAlignment(Qt.AlignCenter)
        self.btn_Actualizar = QPushButton(self.pagina_RE)
        self.btn_Actualizar.setObjectName(u"btn_Actualizar")
        self.btn_Actualizar.setGeometry(QRect(200, 380, 191, 23))
        self.btn_Actualizar.setStyleSheet(u"border-radius: 10px;\n"
"background-color: rgb(91, 91, 91);")
        

        
        self.stackedWidget.addWidget(self.pagina_RE)

        


        self.pagina_Actualizar_2 = QFrame(self.centralwidget)
        self.pagina_Actualizar_2.setObjectName(u"pagina_Actualizar_2")
        self.pagina_Actualizar_2.setGeometry(QRect(-1, -1, 651, 431))
        self.pagina_Actualizar_2.setFrameShape(QFrame.StyledPanel)
        self.pagina_Actualizar_2.setFrameShadow(QFrame.Raised)
        self.label_14 = QLabel(self.pagina_Actualizar_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(30, 150, 47, 13))
        self.TXT_PRECIO_3 = QLineEdit(self.pagina_Actualizar_2)
        self.TXT_PRECIO_3.setObjectName(u"TXT_PRECIO_3")
        self.TXT_PRECIO_3.setGeometry(QRect(90, 180, 151, 20))
        self.TXT_PRECIO_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_15 = QLabel(self.pagina_Actualizar_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(30, 90, 201, 16))
        self.label_15.setStyleSheet(u"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_16 = QLabel(self.pagina_Actualizar_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(30, 180, 47, 20))
        self.label_17 = QLabel(self.pagina_Actualizar_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(40, 290, 320, 101))
        self.label_17.setStyleSheet(u"font: 75 27pt \"MS Sans Serif\";")
        self.label_18 = QLabel(self.pagina_Actualizar_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 120, 81, 21))
        self.BOTON_ACTUALIZAR_3 = QPushButton(self.pagina_Actualizar_2)
        self.BOTON_ACTUALIZAR_3.setObjectName(u"BOTON_ACTUALIZAR_3")
        self.BOTON_ACTUALIZAR_3.setGeometry(QRect(70, 250, 121, 23))
        self.TXT_CODIGO_3 = QLabel(self.pagina_Actualizar_2)
        self.TXT_CODIGO_3.setObjectName(u"TXT_CODIGO_3")
        self.TXT_CODIGO_3.setGeometry(QRect(90, 120, 151, 20))
        self.TXT_CODIGO_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_19 = QLabel(self.pagina_Actualizar_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 210, 71, 16))
        self.TXT_CANTIDAD_2 = QLineEdit(self.pagina_Actualizar_2)
        self.TXT_CANTIDAD_2.setObjectName(u"TXT_CANTIDAD_2")
        self.TXT_CANTIDAD_2.setGeometry(QRect(90, 210, 151, 20))
        self.TXT_CANTIDAD_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_20 = QLabel(self.pagina_Actualizar_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(130, 50, 411, 31))
        self.TXT_NOMBRE_PRODUCTO_2 = QLineEdit(self.pagina_Actualizar_2)
        self.TXT_NOMBRE_PRODUCTO_2.setObjectName(u"TXT_NOMBRE_PRODUCTO_2")
        self.TXT_NOMBRE_PRODUCTO_2.setGeometry(QRect(210, 90, 151, 20))
        self.TXT_NOMBRE_PRODUCTO_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.BOTON_BUSCAR_3 = QPushButton(self.pagina_Actualizar_2)
        self.BOTON_BUSCAR_3.setObjectName(u"BOTON_BUSCAR_3")
        self.BOTON_BUSCAR_3.setGeometry(QRect(370, 90, 75, 23))
        self.TXT_NOMBRE_3 = QLineEdit(self.pagina_Actualizar_2)
        self.TXT_NOMBRE_3.setObjectName(u"TXT_NOMBRE_3")
        self.TXT_NOMBRE_3.setGeometry(QRect(90, 150, 151, 20))
        self.TXT_NOMBRE_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.stackedWidget.addWidget(self.pagina_Actualizar_2)

        
        self.pagina_ELIMINAR = QWidget()
        self.pagina_ELIMINAR.setObjectName(u"pagina_ELIMINAR")
        self.stackedWidget.addWidget(self.pagina_ELIMINAR)

        self.verticalLayout_2.addWidget(self.stackedWidget)


        self.horizontalLayout.addWidget(self.frame_3)


        self.verticalLayout.addWidget(self.frame_2)

        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 9)
        
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.BOTON_LOGO.setText(QCoreApplication.translate("MainWindow", u"SUMAQ RUNAKAY", None))
        self.boton_minimizar.setText("")
        self.boton_eliminar.setText("")
        self.BOTON_TABLA.setText(QCoreApplication.translate("MainWindow", u"TABLA", None))
        self.BOTON_rEGISTRAR.setText(QCoreApplication.translate("MainWindow", u"  INVENTARIO", None))
        self.BOTON_ACTUALIZAR.setText(QCoreApplication.translate("MainWindow", u"ACTUALIZAR", None))
        self.BOTON_eLIMINAR.setText(QCoreApplication.translate("MainWindow", u" ELIMINAR", None))
        self.Btn_Siguiente.setText(QCoreApplication.translate("MainWindow", u"Siguiente", None))
        self.Btn_6.setText("")
        self.Btn_9.setText("")
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Codigo", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Producto", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Precio", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Cantidad", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Subtotal", None));
        self.Btn_1.setText("")
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Punto de Venta", None))
        self.Btn_7.setText("")
        self.Btn_12.setText("")
        self.Btn_8.setText("")
        self.Btn_4.setText("")
        self.Btn_10.setText("")
        self.Btn_5.setText("")
        self.Btn_Eliminar.setText(QCoreApplication.translate("MainWindow", u"Eliminar", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Cantidad:", None))
        self.push.setText(QCoreApplication.translate("MainWindow", u"Agregar", None))
        self.Btn_3.setText("")
        self.Btn_11.setText("")
        self.Btn_2.setText("")
        
        self.label_14.setText(QCoreApplication.translate("Form", u"NOMBRE:", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"CODIGO DE INVENTARIO:", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"PRECIO:", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"CODIGO:", None))
        self.TXT_CODIGO_3.setText(QCoreApplication.translate("Form", u"", None))
        self.BOTON_ACTUALIZAR_3.setText(QCoreApplication.translate("Form", u"ACTUALIZAR", None))
        self.BOTON_BUSCAR_3.setText(QCoreApplication.translate("Form", u"ACTUALIZAR", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"CANTIDAD:", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">ACTUALIZAR PRODUCTO</span></p><p align=\"center\"><br/></p></body></html>", None))



        ___qtablewidgetitem = self.tabla_inventario.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Codigo", None));
        ___qtablewidgetitem1 = self.tabla_inventario.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Cod_Producto", None));
        ___qtablewidgetitem2 = self.tabla_inventario.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Nom_Producto", None));
        ___qtablewidgetitem3 = self.tabla_inventario.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Stock", None));
        ___qtablewidgetitem4 = self.tabla_inventario.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Precio_Unidad", None));
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; font-style:italic;\">Inventario</span></p></body></html>", None))
        self.btn_Actualizar.setText(QCoreApplication.translate("MainWindow", u"ACTUALIZAR", None))
    # retranslateUi
